name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: citizen-of-planet-earth/cf-cli-action@master
          with:
            cf_api: https://api.au-syd.cf.cloud.ibm.com
            cf_username: ${{ secrets.CF_USER }}
            cf_password: ${{ secrets.CF_PASSWORD }}
            cf_org: rocketpunch
            cf_space: dev
            command: push -f manifest-dev.yml
